#!/bin/bash

docker login
if [ $? != 0 ]; then
	exit
fi

./version.local $1

git add *
git commit
git push

./build.local $1

docker tag redmine-git:$1 redmine-git

docker push buxis/redmine-git:$1
docker push buxis/redmine-git

docker tag redmine-git:$1 buxis/redmine-git:$1
docker tag redmine-git buxis/redmine-git

docker logout

