#!/bin/bash

docker login
if [ $? != 0 ]; then
	exit
fi

./version.local $1

#git add *
#git commit
#git push

./build.local $1

docker tag redmine-git-hosting:$1 redmine-git-hosting

docker push gledsoncruz/redmine-git-hosting:$1
docker push gledsoncruz/redmine-git-hosting

docker tag redmine-git-hosting:$1 gledsoncruz/redmine-git-hosting:$1
docker tag redmine-git-hosting gledsoncruz/redmine-git-hosting

docker logout

