#!/bin/bash

	-t $IMAGE_NAME:3.3.3.1 .

echo "Build hook running"
docker build --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
	--build-arg VCS_REF=`git rev-parse --short HEAD` \
	--build-arg REDMINE_GIT_VERSION=3.3.3.1 \
	-t $IMAGE_NAME:3.3.3.1 .
